[workspace]
members = [
    "dungeon-vr",
    "dungeon-vr-client",
    "dungeon-vr-cryptography",
    "dungeon-vr-dedicated",
    "dungeon-vr-server",
    "dungeon-vr-shared",
    "dungeon-vr-stream-codec",
]
