[package]
name = "steam-audio-sys"
version = "0.1.0"
edition = "2021"
license = "MIT"
links = "phonon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.59"
